apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: toplisting-service-api
  description: The Toplisting Service REST API
  tags:
    - api
  links:
    - url: https://github.com/smg-real-estate/toplisting-service/blob/main/openapi.yml
      title: GitHub Repo
      icon: github
spec:
  type: openapi
  lifecycle: production
  owner: flyingpenguins
  definition:
    $text: https://github.com/smg-real-estate/toplisting-service/blob/main/openapi.yml
