apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: smg-real-estate/toplisting-service
    github.com/team-slug: orgs/smg-real-estate/teams/flyingpenguins
    sonarqube.org/project-key: homegate_toplisting-service
  name: toplisting-service
  description: Manages booking status of toplisting, changed description, changed again
  links:
    - url: https://github.com/smg-real-estate/toplisting-service/
      title: GitHub Repo
      icon: github
spec:
  type: service
  lifecycle: production
  owner: flyingpenguins
  providesApis:
    - toplisting-service-api
    - toplisting-service-harmonized-events
    - toplisting-service-unified-events
  consumesApis:
    - listings-importer-events
    - customer-service-harmonized-events
    - search-api
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: smg-real-estate/toplisting-service
    github.com/team-slug: orgs/smg-real-estate/teams/flyingpenguins
    sonarqube.org/project-key: homegate_toplisting-service
  name: toplisting-service-part-2
  description: Manages aaaaa
  links:
    - url: https://github.com/smg-real-estate/toplisting-service/
      title: GitHub Repo
      icon: github
spec:
  type: service
  lifecycle: production
  owner: flyingpenguins
  providesApis:
    - toplisting-service-api
    - toplisting-service-harmonized-events
    - toplisting-service-unified-events
  consumesApis:
    - listings-importer-events
    - customer-service-harmonized-events
    - search-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: pricing-api
  description: The Pricing REST API
  tags:
    - api
  links:
    - url: https://github.com/smg-real-estate/pricing-api/blob/main/openapi.yml
      title: GitLab Repo
      icon: gitlab
spec:
  type: openapi
  lifecycle: production
  owner: pinkpanthers
  definition:
    $text: https://github.com/smg-real-estate/pricing-api/blob/main/openapi.yml
